In [6]:
import numpy as np
my_list=[1,2,3,4]
arr=np.array(my_list)
arr

array([1, 2, 3, 4])

In [35]:
np.random.randint(0,100,(10,10))

array([[77, 41, 65, 62, 38,  6, 25, 83,  5, 99],
       [66, 94,  3, 44, 17, 53, 90, 59,  0, 42],
       [31, 15,  4, 90, 77, 47, 39, 57, 24, 80],
       [17, 87,  4, 26, 18, 13, 77,  5, 11, 65],
       [99,  2, 46,  2, 19, 20, 72, 58, 66, 51],
       [67, 99, 52, 42, 25, 34, 26,  7, 17, 61],
       [87, 84, 77, 83, 10, 24, 80, 93,  9, 23],
       [55, 88, 22, 33, 21, 86, 76, 38, 27, 96],
       [36, 70, 14, 73, 56, 24, 69, 11, 19, 74],
       [56, 54, 95, 19, 89, 92, 57, 58, 82,  0]])

In [21]:
np.arange(0,10)
np.ones((1,2))

array([[1., 1.]])